### PR TITLE
Address some neglect on sf-em-data

### PR DESCRIPTION
**Pull request by crodriguez1a**
Address some quality issues with `sf-em-data` as mention on #42

### CODE REVIEW

**Comment by CrushedPixel** [comment]
Looks good so far. I'll try and fix the issue of values being displayed in the wrong columns in this branch.

**Review by CrushedPixel — COMMENTED** [review]
Looks good, but doesn't address the proper order of columns in relation to the headings yet, does it?

**Comment by crodriguez1a** [comment]
@CrushedPixel That’s correct. There is only a test written at the moment.

**Comment by crodriguez1a** [comment]
@CrushedPixel Take another look. Re-arranging records as per headings tests are now passing.

**Pull request merged**
